README.md

bring python code highlighting to Readme.md

Sexier Readme

---

instagrapi/mixins/private.py
instagrapi/mixins/public.py

added private requests counter

Lexan73 patch 1

---

instagrapi/mixins/account.py
instagrapi/mixins/album.py
instagrapi/mixins/auth.py
instagrapi/mixins/challenge.py
instagrapi/mixins/collection.py
instagrapi/mixins/comment.py
instagrapi/mixins/direct.py
instagrapi/mixins/hashtag.py
instagrapi/mixins/igtv.py
instagrapi/mixins/insights.py
instagrapi/mixins/location.py
instagrapi/mixins/media.py
instagrapi/mixins/photo.py
instagrapi/mixins/private.py
instagrapi/mixins/user.py
instagrapi/mixins/video.py
instagrapi/story.py

- Add doc comments for all the functions in Mixin classes

Add doc strings for all Mixin classes and functions

---

instagrapi/extractors.py
instagrapi/mixins/story.py

KeyError 'StoryImage' from story_seen() and  IndexError from user_stories_gql()

fix methods story_seen and user_stories_gql

---

instagrapi/__init__.py
instagrapi/exceptions.py
instagrapi/mixins/clip.py

Modified IGTV file for Uploading reels.
Removed - 
Commented and Removed IGTV releated info
Replace -
Replace igtv api to reel api in private request

Implemented posting reels

---

instagrapi/mixins/collection.py

Endpoint is not same for User Created Collection and Default All Posts Collection.

Get All Posts saved medias

---

examples/medias.py

The example was not working as expected.
Fixed using load_settings and dump_settings functions instead of write_file and read_file.

Fix media.py example

---

examples/bot.py

A simple bot implementation for the issue

Add bot.py example [#91]

---

instagrapi/mixins/story.py

common download interface

---

instagrapi/__init__.py
instagrapi/mixins/timeline.py

Methods :
reels = Get connected reels media ( Reels from users you are following )
explore_reels = Get discover reels media

Added support for Reels Timeline

---

instagrapi/mixins/comment.py

Sorry, new to pull requests and made a stupid error. Fixed.

Fixed SyntaxError on previous commit

---

instagrapi/mixins/story.py

sometimes when using user_stories_v1 reel is `None` so I added some conditions to handle it

fix issue on  user_stories_v1 sometimes reel is None

---

instagrapi/mixins/user.py
instagrapi/types.py

method to to check if user follow you and many more  related to #333

add user_friendship_v1 method to get friendship status 

---

instagrapi/mixins/user.py

add support for searching user followers/following  related to #234

add support for searching user followers/following

---

instagrapi/mixins/album.py
instagrapi/mixins/photo.py
instagrapi/mixins/video.py

Hi, I wrote several functions to download without saving to the file.

add download without save to file

---

instagrapi/story.py

Implemented the clip closing in the video() method of StoryBuilder.

---

docs/usage-guide/media.md

Added invite_coauthor_user_id to extra_data when uploading photos

Added coauthor info to docs

---

instagrapi/mixins/fbsearch.py

I found this code in an issue to figure out how to get suggested user by userid, and It works. https://github.com/adw0rd/instagrapi/issues/545 and It works.
I think it will be helpful for others 
credit [abdullahbektass](https://github.com/abdullahbektass)

add fb_search_suggested_profiles function

---

docs/usage-guide/media.md

Just a small documentation change related to [this closed issue](https://github.com/adw0rd/instagrapi/issues/657).

DOC clarify limitation

---

instagrapi/mixins/user.py

https://github.com/adw0rd/instagrapi/issues/760
The bug is fixed by disabling signing of the form.

dont sign form in user_friendships_v1

---

instagrapi/mixins/user.py

I also added `_uuid` to the form.

Fix user_friendships_v1 user_ids form data and added _uuid form data

---

docs/usage-guide/story.md

added story_like & story_unlike to story methods table
added a snippet for story_like and story_unlike

updates story user-guide

---

instagrapi/__init__.py
instagrapi/mixins/fundraiser.py

When you visit your own profile page in the app it makes a call to this endpoint. To be able to replicate this behavior i added this method.

added standalone_fundraiser_info_v1

---

instagrapi/config.py

updated SUPPORTED_CAPABILITIES

---

instagrapi/mixins/video.py

I was coding and I would frequently get a TypeError whenever a link wasn't formatted correctly, and I fixed it. I made a detailed guide on how to navigate the error if a user stumbles upon it so future users don't have to struggle so much.

Added a detailed error message to help users fix an error.

---

instagrapi/mixins/account.py

**New functions**
- account_set_private -> It makes the account private
- account_set_public -> It makes the account public

Adding new functions to account.py 

---

instagrapi/extractors.py
instagrapi/types.py

I added paid partnership (sponsor_tags) for story and post, comment_disabled (for posts), and story sticker link.
After using lamadava.com services, I realized there are some field which extractors and types in instagrapi client don't support, and thus the Lamadava api doesn't provide them. So I added the fields to "types" and "extractors".
Added fields and types:
- **sponsor_tags** (paid partnership) added to "Story" and "Media"
- **comments_disabled** added to "Media"
- **StoryStickerLink** added to "StorySticker" (story_link field)

Add some missing fields to story and media

---

instagrapi/mixins/auth.py
instagrapi/mixins/media.py

-User agent saved to settings.
-If there is no timeout between page iterations, it is set to be randomly assigned.

Some improvements

---

instagrapi/mixins/clip.py
tests.py

I added the function to create reels from a video and add custom music to it.
Also, it contains the metadata to add the music title to any video which already has music under it.

Adding reel with music

---

instagrapi/mixins/private.py

Fix typo in error message

---

instagrapi/extractors.py

I have added this code 
Instead of this 
Fetching the hd version from the second one first, anyways I am new to py and flask so unable to find it in `user_info_by_username()`
Anyways I have added here `user_info_by_username_v1()`
Do check and let me know what we can do @adw0rd

Changed the HD Profile Picture value - user_info_by_username_v1

---

.github/workflows/python-package.yml
README.md
docs/usage-guide/notes.md
setup.py

Fixed python version for GitHub Action
Edited README.md

Made documentation for note, Changed version in setup.py,

---

instagrapi/mixins/clip.py
instagrapi/mixins/collection.py

Really similar to https://github.com/adw0rd/instagrapi/pull/1143 (+ a little isort fix for CI)

media_save without media_user

---

instagrapi/extractors.py
instagrapi/types.py

Hi there!
Thank you for sharing your repository with us.
I wanted to let you know that I just made a new update to the codebase that adds support for audio messages. This means that you can now download audio messages by using the new "audio_url" attribute.
Let me know if you have any questions or feedback on the changes. Thanks again!

added voice_media url if there is audio in message

---

instagrapi/__init__.py
instagrapi/mixins/explore.py

Closes https://github.com/adw0rd/instagrapi/issues/711
Adding a mixin to get the content of the explore page and report media on the explore page

Add explore mixin

---

instagrapi/mixins/location.py

A fix to the pagination bug in the location_medias_v1_chunk.

Fix for location_medias_v1_chunk pagination

---

instagrapi/mixins/video.py

Fixed the original code, as it causes another error when used.

Updated error message

---

instagrapi/mixins/media.py

add user pinned medias
https://github.com/adw0rd/instagrapi/issues/1259

add user pinned medias

---

instagrapi/mixins/direct.py

this is a fix for direct_send , it does not working and throw Client error
https://github.com/adw0rd/instagrapi/issues/1281

fix for direct_send

---

instagrapi/mixins/auth.py

For [issue](https://github.com/adw0rd/instagrapi/issues/1287)
This route broke all versions of the library when you log in not through a session

Fix 429 response

---

instagrapi/mixins/direct.py

Fixes direct_message_delete()

---

instagrapi/mixins/auth.py

Change json file human readable

add indent to login setting json file

---

README.md
instagrapi/extractors.py
instagrapi/types.py
setup.py

- added type for xma_share in direct messages
- referencing #1137 
- bumped version number and last reverse-engineering date
this is an example for an xma_media_share answer from instgram
```json
{
"xma_media_share": [
{
"xma_template_type": "None",
"xma_layout_type": 0,
"preview_url": "https://scontent.cdninstagram.com/v/t51.2885-15/237322268_339474187870479_995152229607522908_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=8ae9d6&_nc_ohc=O5KO_SzSck4AX8xdcod&_nc_ad=z-m&_nc_cid=0&_nc_ht=scontent.cdninstagram.com&oh=00_AfDMZnyOdELu7JU-imvtIhdAsV5_uvvYxSjUgVTPWUrjgA&oe=64A02494&ig_cache_key=MjY0MTYxNjAyMjI1ODY0MTIxNA%3D%3D.2-ccb7-5",
"preview_url_mime_type": "image/jpeg",
"preview_width": 1080,
"preview_height": 1080,
"title_text": "get_rightcs 🖐️🥳 Well, I think this might be a first for me ...", …
```

added xma_share type

---

instagrapi/mixins/direct.py

Behind the scenes, Instagram Application gathering threads in chunks. Adding _direct_threads_chunk()_ method brings more flexibility for devs and still leaves the opportunity to use _direct_threads()_ method just as before.

Gathering direct threads in chunks

---

instagrapi/mixins/challenge.py

If the account does not have a birthday, enter a random birthday over the age of 18.

Birthday challenge

---

instagrapi/mixins/challenge.py

Referencing to #1462 - checking new "verify_email_code" step_name.
Referencing to #1460 - module random was not imported, would have caused an error.

New verify_email_code step. Import random module.

---

README.md

This pull request enhances the project's usability by introducing a comprehensive installation guide, ensuring a seamless setup for all users. Additionally, I've diligently corrected typos in the README.md file, enhancing its readability. Let's make collaborating on this project even smoother! 🛠️

📝 Added Installation Guide & Fixed Typos in README.md

---

instagrapi/mixins/direct.py

New method allows users find all the threads with mentioned query

direct_message_search() method added

---

instagrapi/mixins/note.py

File "instagrapi/mixins/note.py", line 4, in <module>
File "instagrapi/mixins/note.py", line 5, in NoteMixin
TypeError: 'type' object is not subscriptable

fix: TypeError: 'type' object is not subscriptable.

---

docs/usage-guide/notes.md
tests.py

Updated Documentation for NoteMixin

Notes docs + test updated.

---

README.md
docs/index.md
instagrapi/mixins/fbsearch.py

Method to retrieve recent search results

Slight docs update + new fbsearch method

---

instagrapi/mixins/direct.py

1. Added thread approve for the thread in Requests box. 
2. Added ability to gather Spam inbox (Hidden requests inbox).
3. Updated marking thread as seen functionality. direct_message_seen() brings more flexibility to the devs, as method direct_send_seen() requires additional request on thread, which is in most cases unnecessary, since threads could be (and usually are) retrieved in other requests, such as direct_threads()
4. Updated direct_thread_hide(). Ability to move thread to Spam Inbox.

Direct updates

---

instagrapi/mixins/direct.py
instagrapi/mixins/user.py
instagrapi/types.py

Tested on both "profile" and "direct_thread_info" surfaces

Block and unblock user methods
