subzeroid/instagrapi

- instagrapi/mixins/auth.py
After the session is restored, only requests via the private_request() method will work, since the headers for the request are initialized there via _send_private_request().
in the same requests as, for example, in photo_upload(), requests to self.private() / requests.Session() go directly without initializing headers.
Unfortunately, we had to break the encapsulation rule and initialize the headers in auth.py, otherwise it would be necessary to change all the methods that send requests and work with requests.Session() directly without an intermediary.
Fix #367
> Correction of an error related to session recovery.

- docs/usage-guide/direct.md
- instagrapi/mixins/direct.py
Hello!
I found your repository by chance and I really liked it.
Doing some tests in your lib, I noticed that the ```direct_threads()``` method doesn't set the limit of messages that will bring inside a thread. I believe this can make the request a little slower as it also has post-processing to transform the server's response to higher level objects.
So I added the optional ```thread_message_limit: int``` parameter to the method that brings up the threads. Since you have the ```direct_messages(thread.pk)``` method, I think the programmer might want to limit the amount of thread messages, I don't know, maybe to 5.
Do you think this modification makes sense for the project?
PS: I changed the documentation of the direct module. I added the ```selected_filter``` parameter and the …
> Add thread_message_limit param in direct_threads()

- instagrapi/mixins/auth.py
Hi, @adw0rd.
Currently `master` branch has multiple issues with 2FA authentication.
**Description**: Currently 2FA always fails with `This code is no longer valid. Please request a new one.` error.
**What's wrong**: You're send `uuid` in the second request to  `api/v1/accounts/two_factor_login/` in the `device_id` field, instead of expected `android_device_id`, but in the first login request you sent correct `android_device_id` in this field to `api/v1/accounts/login/` path.
**Referenced issues**: #276, #362
First login request `device_id` field:
https://github.com/adw0rd/instagrapi/blob/d78529939c5611ae030ecdec4d6e93fc01888906/instagrapi/mixins/auth.py#L388
Second 2FA request `device_id` field:
https://github.com/adw0rd/instagrapi/blob/d78529939c5611ae030ecdec4d6e93fc01888906/instagrapi/m …
> Fixed 2FA authentication

- docs/usage-guide/interactions.md
When addressing the proxy via hostname I had to use `socks5h` instead of just `socks5`; found it in this thread https://stackoverflow.com/a/43266186 This might help other users as well.
> Adding another example of using socks proxy

- instagrapi/mixins/media.py
Only call location_complete within media_info_gql if the shortcode_media has location AND authorization exists.
Potentially resolves #653
> Add auth condition when calling location_complete

- instagrapi/mixins/photo.py
Allows you to mention several accounts, with the given coordinates in StoryMention().
> Update of photo.py for mentions

- instagrapi/mixins/direct.py
This method uses the endpoint for getting all media from a DM thread. Much faster for getting all media than direct_thread method.
> Add method for getting all media from DM thread

- instagrapi/__init__.py
- instagrapi/mixins/multiple_accounts.py
These endpoints seem to be legacy since logging into multiple accounts with one set of credentials is no longer accessible. It should still work for people who used it in the past. https://help.instagram.com/615080698917740?__coig_restricted=1
The reason for this pull request is that the app still calls these endpoints.
A call to `multiple_accounts/get_account_family/`is being made after logging in. 
And `multiple_accounts/get_featured_accounts/` when viewing an profile where the `target_user_id` parameter is the user id of the account you are viewing.
Maybe somebody who has used this feature in the past can expand on these settings. I think its good to include them just to make your client look more like the legit app.
> Added MultipleAccountsMixin

- instagrapi/__init__.py
Otherwise, if not provided, falls back to the default logger.
> Client accepts logger as instantiation arg

- .gitignore
- docs/usage-guide/comment.md
- instagrapi/mixins/comment.py
This pull request integrates the `media_comments_chunk` method that can allow us to get paginated comments.
I think that can be useful when you're trying to fetch comments from a media that has a lot of them, and you want to split the workload between accounts in order to not trigger Instagram scrape limitations.
(I also changed a wording in the `media_comments` method's doc. The other changes are just due to the lint)
> media_comments_chunk

- instagrapi/mixins/media.py
The use of `media_id` in the `media_likers` function was triggering the `media_info` and `media_user` functions, which is useless because the endpoint `https://i.instagram.com/api/v1/media/<media_pk>/likers/` is returning the same output as `https://i.instagram.com/api/v1/media/<media_pk>_<user_id>/likers/` so this PR reduces a lot the number of requests and time of using `media_likers`.
> media_likers enhancement

- instagrapi/extractors.py
Using `user_medias` I noticed `thumbnail_url` was containing a cropped/low-quality image when the media type was a simple photo. I don't think it's very useful to return the actual thumbnail, the full size image is better imo.
It makes sense to keep "thumbnail" name because in case the media type is a video, `thumbnail_url` is still a thumbnail (because it's an image), but at least it's in its biggest size-format and highest quality.
> full size image when available

- instagrapi/extractors.py
This prevents an exception that sometimes occurs when is neither `hd_profile_pic_url_info` nor `hd_profile_pic_versions`.
> fix: prevent exception in extract_user_v1 when no hd profile pic exists

- instagrapi/mixins/private.py
`/challenge/` appears to no longer exist however, `/v1/challenge/` does. Tested on my own account(s) and it works.
> Created endpoint check for /challenge/ fixing 2FA

- instagrapi/mixins/private.py
- instagrapi/mixins/public.py
`request_logger` was always "public_request" even when it should be "private_request"
> distinct logger

- .gitignore
- instagrapi/__init__.py
- instagrapi/config.py
- instagrapi/exceptions.py
- instagrapi/extractors.py
- instagrapi/mixins/auth.py
- instagrapi/mixins/note.py
- instagrapi/types.py
- tests.py
You can now send Note using Instagrapi !
To use it juste import NoteMixin and use the function send_note it will require two arguments :
```python
send_note(note_content, audience)
```
| Parameter | Type     | Description                |
| :-------- | :------- | :------------------------- |
| `note_content` | `string` | The content of your note. **Max size : 60** |
| `audience`      | `int` | The type of audience you want you note to be visible |
In order to use this, you should set your Instagram version in the user agent as `265.0.0.19.301` this is the version where Notes has been implemented.
You can learn more about the new Note functionality [here](https://about.instagram.com/blog/announcements/updates-to-instagram-messenger-and-stories/)
This code is highly experimental being my …
> Note functionality

- instagrapi/mixins/user.py
Just adding following_v1_chunk method.
I know that [PR](https://github.com/adw0rd/instagrapi/pull/544) that contains same contents but the PR seems not to be merged
> Adding following_v1_chunk method same as for followers

- instagrapi/mixins/media.py
Liking a media doesn't seem to require a "full" media_id with the user pk appended to it.
In other term `2277033926878261772` is enough and work as much as `2277033926878261772_1903424587`.
With this PR, liking a media is much quicker and requires less data fetching.
> media_like without media_user

- instagrapi/mixins/auth.py
Since b64part can be empty `""` when trying re login, We need an if statement to prevent runtime exception
> Add an exception handler for parse_authorization function

- instagrapi/mixins/comment.py
- instagrapi/mixins/explore.py
- instagrapi/mixins/hashtag.py
- instagrapi/types.py
Hi, 
If wanted, you can review/merge our PR. 
We added some little things we found are different from instagrams app requests.
First of all, `comments_disabled` only works for some cases were comments are disabled. We added `comments_disabled_for_viewer`, which also needs to be checked.
There was a missing / after `discover/topical_explore` which instagram responded with a redirect. Might not matter, but still added it in case it would flag the account.
We added `check_offensive_comment`, which is a request that gets send before you comment on a media. So that one should probably be called before commenting.
`hashtag_medias_v1_chunk` requests to an endpoint which, according to the instagram app,  wants all keys in supported keys, not only the picked one. Also added the missing "clips" key
> More features / missing / fixes

- instagrapi/mixins/media.py
The clips function wasn't using the cursor so it would never get more pages.
> add next_max_id to get_clips_paginated_v1 params

- instagrapi/mixins/explore.py
- instagrapi/types.py
Adding a method for getting media info from the explore page. 
I noticed that while using Proxyman on the explore page of my instagram, that it was calling this endpoint instead of the normal media_info endpoint to get details about media.
> Adding explore page media info

- instagrapi/mixins/challenge.py
This `elif` statement in `challenge.py` will handle the `ChallengeUnknownStep` error that was occurring due to a new challenge type `select_contact_point_recovery` which was previously unhandled. Some extra todo comments are left if that functionality wants to be added in the future.
> fix for ChallengeUnknownStep error "select_contact_point_recovery"

- instagrapi/mixins/private.py
- instagrapi/mixins/public.py
This adds a retry strategy to the public and private instagrapi requests that will retry a request up to 3 times if the server returns an error status code of 429, 500, 502, 503, or 504, and if the HTTP method is GET or POST. The wait time between each retry will increase x2 each time.
instead of users needing to handle retries downstream they can rely on the retries here
> Setup request strategy for private and public requests

- instagrapi/mixins/challenge.py
- instagrapi/mixins/private.py
- instagrapi/mixins/public.py
- instagrapi/mixins/story.py
Removing method "method_whitelist" from Retry, since it's gonna be deprecated in v2.
Adding sticker_tray loader request. This request is executed by Instagram application each time you want to add sticker to the story.
Closing challenge_resolve before verifying account details. Referenced to #1354
> Some updates

- instagrapi/mixins/direct.py
Referencing to #1448 - adding pending inbox chunk method.
> Gathering pending inbox in chunks

- instagrapi/mixins/photo.py
This pull request introduces enhancements to the Instagram API functions related to photo uploads, specifically photo_rupload and photo_upload. The changes are aimed at preventing potential errors and ensuring compatibility with Instagram's allowed file formats. Solving #1456
The key enhancements include:
File Format Validation: A file format validation check has been implemented in the photo_rupload function. It verifies that the provided file is in either JPG or JPEG format, which are the only formats supported by Instagram. This validation helps prevent errors during the upload process and ensures that only compatible files are processed.
Error Handling Improvement: The error handling mechanism in photo_rupload has been improved. If an invalid file format is detected, a ValueError is …
> File Format Validation and Error Handling Enhancements Solves #1456

- instagrapi/mixins/direct.py
Opportunity to choose box (general or primary) to get threads from (only applies to business accs). Not passing a parameter does not affect behavior for non-business accounts.
>  General or Primary box for direct_threads()

- instagrapi/mixins/auth.py
- instagrapi/mixins/direct.py
**### Some of the latest API changes of Instagram version 292.0.0.31.110**
1. _direct_send() - new data attributes + ability to set send_attribute value._
2. _direct_search() - updated data attributes + ability to set search mode. Response does not contain threads info, only users + fb suggestions._
3. _direct_thread_by_participants() - response does not contain thread info, but has User data. (Look around retrieving users, as no extract method suits response)_
4. _direct_users_presence() - added new method to get presence of particular user. Response - Dict_
5. _get_timeline_feed() - updated data attributes + ability to set max_id (for paginating); Added reason options_
6. _get_reels_tray_feed() - updated data attributes + added reason options_
**Manually tested all the updated methods, …
> Updating direct and feed/reels methods

- README.md
Before, clicking the badge just opened the image. Now, it opens the PyPI project.
I was trying to use it several times, so I thought, I'd just go ahead and finally fix it.
> Fix PyPI badge link in README.md

- instagrapi/extractors.py
- instagrapi/mixins/direct.py
- instagrapi/mixins/note.py
- instagrapi/mixins/user.py
- instagrapi/types.py
Minor changes in PR:
1. Fixed type hint of the recently added direct_message_search() (#1521)
2. Added Return description in direct_users_presence() (#1482)
3. Added creator_info() (probably, separated CreatorMixin needed as there are some more /creator/ methods unexplored)
Major changes done in NoteMixin and related:
1. Removed NoteRequest and NoteResponse from types.py. Instead, left just Note class (status field removed as it's only received on creation, indicating success of the action).
2. Remove extract_note() as not a single method requires an extractor.
3. Removed uuid import, as no need in generating one for requesting.
4. Added docs to every single method.
5. Added response parsing: create_note(), get_notes() returning Note and List[Note]; delete_note() + last_seen_update_note() …
> Active presence and Notes update

- docs/usage-guide/highlight.md
- docs/usage-guide/media.md
- docs/usage-guide/story.md
- docs/usage-guide/user.md
- instagrapi/mixins/auth.py
- instagrapi/mixins/fundraiser.py
- instagrapi/mixins/highlight.py
- instagrapi/mixins/media.py
- instagrapi/mixins/multiple_accounts.py
- instagrapi/mixins/story.py
- instagrapi/types.py
This pull request addresses an inconsistency in the type annotation for the `user_id` parameter across the codebase. Currently, the functions that interact with a user's ID use different type expectations, leading to potential inconveniences when handling the `user_id` parameter.
Throughout the codebase, the user's ID is fetched using `user_id_from_username`, which returns a string. However, other functions that accept `user_id` as an argument expect it to be an integer.
```python
def user_id_from_username(self, username: str) -> str: ...
```
To enhance consistency and improve code readability, this pull request introduces a uniform type annotation for the `user_id` parameter. We will ensure that all functions that take `user_id` as an argument will accept either a string or an integer, …
> Refactor: inconsistent type annotation for user_id
